apps/urls.py
from django.urls import path, re_path

from apps.views import AllProductListView, LogoutView, ProfileTemplateView, ProfileUpdateView, \
    PasswordUpdateView, ProductListView, ProductSearchListView, \
    MarketListView, MyStreamsListView, StreamCreateView, \
    StatisticsListView, MyOrdersTemplateView, OrderDetailView, LoginRegisterView, ProductStatisticListView, \
    RequestListView, CompetitionListView, DiagramTemplateView, \
    AdminPageTemplateView, OrderListView, OperatorOrderDetail, UserPhotoUpdateView, get_districts_by_region, \
    PaymentListView, CurrierListView, CurrierDetail
from apps.views.product_views import ProductStreamDetail
from apps.views.shop_views import AddOrderCreateView
from apps.views.transaction_views import PaymentFormView

urlpatterns = [

    # products - categories
    path('', AllProductListView.as_view(), name='main-page'),
    path('category', ProductListView.as_view(), name='category'),
    path('product-statistic/<int:pk>', ProductStatisticListView.as_view(), name='product_statistic'),
    re_path(r'^product/(?P<slug>[-\w\u0400-\u04FF]+)/$', ProductStreamDetail.as_view(), name='product-detail'),
    path('success-product/<int:pk>', OrderDetailView.as_view(), name='order-detail'),
    path('ordered-products', MyOrdersTemplateView.as_view(), name='ordered-products'),
    path('search/', ProductSearchListView.as_view(), name='product-search'),
    # path('product-search/', product_search, name='product_search'),

    # streams
    path('stream', MyStreamsListView.as_view(), name='stream'),
    path('stream-create', StreamCreateView.as_view(), name='stream_create'),
    path('stream/<int:pk>', ProductStreamDetail.as_view(), name='stream_detail'),
    path('statistic', StatisticsListView.as_view(), name='statistic'),
    path('market', MarketListView.as_view(), name='market'),

    # transaction
    path('payment-history', PaymentListView.as_view(), name='payment_history'),
    path('payment-form', PaymentFormView.as_view(), name='payment_form'),

    # operator
    path('operator', OrderListView.as_view(), name='operator'),
    path('operator/orders/currier-list', CurrierListView.as_view(), name='currier_list'),
    path('operator/ordered-info/<int:pk>', CurrierDetail.as_view(), name='ordered_info_detail'),
    path('operator/product-add', AddOrderCreateView.as_view(), name='operator_product_add'),
    path('operator/<str:status>', OrderListView.as_view(), name='operator'),
    path('operator/order/<int:pk>', OperatorOrderDetail.as_view(), name='operator-order-detail'),

    # currier

    # auth
    path('admin-page', AdminPageTemplateView.as_view(), name='admin_page'),
    path('login', LoginRegisterView.as_view(), name='login-page'),
    path('logout', LogoutView.as_view(), name='logout-page'),
    path('users/profile', ProfileTemplateView.as_view(), name='profile'),
    path('users/profile-settings', ProfileUpdateView.as_view(), name='profile-settings'),
    path('users/photo-settings', UserPhotoUpdateView.as_view(), name='photo-settings'),
    path('users/password-change', PasswordUpdateView.as_view(), name='pass-settings'),
    path('logout', LogoutView.as_view(), name='logout-page'),

    # shop
    path('requests', RequestListView.as_view(), name='requests'),
    path('competition', CompetitionListView.as_view(), name='competition'),
    path('diagrams', DiagramTemplateView.as_view(), name='diagrams'),
    path('get_districts_by_region/<int:region_id>', get_districts_by_region, name='get_districts_by_region')
]

root/urls.py
from debug_toolbar.toolbar import debug_toolbar_urls
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, re_path
from django.urls import path
from django.utils.translation import gettext_lazy as _

from root.settings import STATIC_URL, STATIC_ROOT, MEDIA_URL, MEDIA_ROOT

admin.site.index_title = _('My Index Title')
admin.site.site_header = _('1000 xil Administration')
admin.site.site_title = _('My Site Management')

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
    path("", include('apps.urls')),
    prefix_default_language=True
) + static(STATIC_URL, document_root=STATIC_ROOT) + static(MEDIA_URL, document_root=MEDIA_ROOT) + debug_toolbar_urls()

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        re_path(r'^rosetta/', include('rosetta.urls'))
    ]

apps/models/product.py
import re

from django.core.exceptions import ValidationError
from django.db.models import PositiveIntegerField, ImageField, CharField, ForeignKey, CASCADE, TextChoices, TextField, \
    DateTimeField, BooleanField
from django.utils.functional import cached_property
from django.utils.translation import gettext_lazy as _
from django_ckeditor_5.fields import CKEditor5Field

from apps.models import SiteSettings, User
from apps.models.base import TimeSlugBased, TimeBasedModel


class Product(TimeSlugBased):
    price = PositiveIntegerField(verbose_name=_('Price'), help_text=_("In sum"))
    photo = ImageField(verbose_name=_('Photo'), upload_to='products/%Y/%m/%d')
    quantity = PositiveIntegerField(verbose_name=_('Quantity'))
    discount = CharField(verbose_name=_('Discount'), max_length=255, null=True, blank=True)
    category = ForeignKey('apps.Category', CASCADE, verbose_name=_('Category'))
    description = CKEditor5Field(verbose_name=_('Description'))
    owner = ForeignKey('apps.User', CASCADE, verbose_name=_('Mahsulotning Egasi'))
    product_fee = PositiveIntegerField(verbose_name=_('Product fee'), help_text=_("In sum"), null=True, blank=True)
    manager_fee = PositiveIntegerField(verbose_name=_('Admin_profit'), help_text=_("In sum"), null=True, blank=True)

    class Meta:
        verbose_name = _('Product')
        verbose_name_plural = _('Products')

    @property
    def new_price(self):
        return self.price - self.product_fee


class DescriptionImage(TimeBasedModel):
    product = ForeignKey(Product, on_delete=CASCADE, related_name='description_images',
                         verbose_name=_('Product'))
    image = ImageField(upload_to='products/descriptions/%Y/%m/%d', verbose_name=_('Description Image'))

    class Meta:
        verbose_name = _('Description Image')
        verbose_name_plural = _('Description Images')

    def __str__(self):
        return f"Image for {self.product.name}"


class Order(TimeBasedModel):
    class Status(TextChoices):
        NEW = 'new', 'New'
        ARCHIVED = 'archived', 'Archived'
        READY_TO_DELIVER = 'ready_to_deliver', 'Ready to deliver'
        DELIVERING = 'delivering', 'Delivering'
        DELIVERED = 'delivered', 'Delivered'
        BROKEN = 'broken', 'Broken'
        RETURNED = 'returned', 'Returned'
        CANCELED = 'canceled', 'Canceled'
        WAITING = 'waiting', 'Waiting'

    quantity = PositiveIntegerField(verbose_name=_('Quantity'), default=1, null=True, blank=True)
    status = CharField(verbose_name=_('Status'), max_length=50, choices=Status.choices, default=Status.NEW)
    full_name = CharField(verbose_name=_('Fullname'), max_length=50, null=True, blank=True)
    phone = CharField(verbose_name=_('Phone'), max_length=20)
    stream = ForeignKey('apps.Stream', CASCADE, null=True, blank=True, related_name='orders', verbose_name=_('Stream'))
    product = ForeignKey('apps.Product', CASCADE, related_name='orders', verbose_name=_('Product'))
    owner = ForeignKey('apps.User', CASCADE, null=True, blank=True, verbose_name=_('Owner'), related_name='orders')
    operator = ForeignKey('apps.User', CASCADE, limit_choices_to={'type': 'operator'}, null=True, blank=True,
                          related_name='operator_orders', verbose_name=_('Operator'))
    currier = ForeignKey('apps.User', CASCADE, limit_choices_to={'type': 'currier'}, null=True, blank=True,
                         related_name='currier_orders', verbose_name=_('Currier'))
    region = ForeignKey('apps.Region', CASCADE, null=True, blank=True, verbose_name=_('Region'))
    district = ForeignKey('apps.District', CASCADE, null=True, blank=True, verbose_name=_('District'))
    comment = TextField(verbose_name=_('Comment'), null=True, blank=True)
    manzil = TextField(verbose_name=_('Manzil'), null=True, blank=True)
    address = CharField(_('Address'), max_length=255, null=True, blank=True)
    send_date = DateTimeField(verbose_name=_('Send date'), blank=True, null=True)
    is_product_fee_added = BooleanField(verbose_name=_('Is product fee added'), null=True, blank=True, default=False)

    def clean_fields(self, exclude=None):
        self.phone = re.sub(r'[^\d]', '', self.phone)
        if len(self.phone) > 9:
            self.phone = self.phone[-9:]
        if len(self.phone) != 9:
            raise ValidationError(_('Incorrect phone number'))
        return super().clean_fields(exclude)

    def save(self, *args, force_insert=False, force_update=False, using=None, update_fields=None):
        if self.stream and self.status == Order.Status.DELIVERED and not self.is_product_fee_added:
            site_settings = SiteSettings.objects.values()[0]
            stream_owner = self.stream.owner, (self.product.product_fee - self.stream.discount) * self.quantity
            _operator = self.operator, site_settings['fee_for_operator']
            _currier = self.currier, site_settings['fee_for_currier']
            if stream_owner[0] == _operator[0]:
                stream_owner[0].balance += (stream_owner[1] + _operator[1])
                _currier[0].balance += _currier[1]
                stream_owner[0].save()
                _currier[0].save()
            elif stream_owner == _currier:
                stream_owner[0].balance += (stream_owner[1] + _currier[1])
                _operator[0].balance += _operator[1]
                stream_owner[0].save()
                _operator[0].save()
            else:
                stream_owner[0].balance += stream_owner[1]
                _operator[0].balance += _operator[1]
                _currier[0].balance += _currier[1]
                stream_owner[0].save()
                _operator[0].save()
                _currier[0].save()
            self.is_product_fee_added = True

        if self.status == Order.Status.DELIVERED and not self.is_product_fee_added and str(
                self.product.owner) == '999999999':
            site_settings = SiteSettings.objects.values()[0]
            # _currier = self.currier, site_settings['fee_for_currier']

            manager = User.objects.filter(type=User.Type.MANAGER).first()
            _currier = self.currier, site_settings['fee_for_currier']

            if manager:
                manager.balance += (self.product.manager_fee * self.quantity)
                _currier[0].balance += _currier[1]
                manager.save()
                _currier[0].save()
                self.is_product_fee_added = True

        if self.status == Order.Status.DELIVERED and not self.is_product_fee_added and str(
                self.product.owner) == '979631626':
            site_settings = SiteSettings.objects.values()[0]
            manager1 = User.objects.filter(type=User.Type.MANAGER, phone='990501655').first()
            _currier = self.currier, site_settings['fee_for_currier']
            if manager1:
                manager1.balance += (self.product.manager_fee * self.quantity)
                _currier[0].balance += _currier[1]

                manager1.save()
                _currier[0].save()
                self.is_product_fee_added = True

        super().save(*args, force_insert=force_insert, force_update=force_update, using=using,
                     update_fields=update_fields)

    @cached_property
    def price_conclude(self):
        if self.stream:
            if self.quantity:
                return (self.product.price - self.stream.discount) * self.quantity
            return self.product.price - self.stream.discount
        else:
            if self.quantity:
                return self.product.price * self.quantity
            return self.product.price

    @cached_property
    def price_(self):
        if self.stream:
            return self.product.price - self.stream.discount
        return self.product.price

    @cached_property
    def delivery_price(self):
        settings = SiteSettings.objects.values('tashkent_city', 'tashkent_region', 'other_regions')[0]
        if self.district:
            if self.region.pk == 14:
                return settings['tashkent_city']
            if self.region.pk == 11:
                return settings['tashkent_region']
            return settings['other_regions']

    class Meta:
        verbose_name = _('Order')
        verbose_name_plural = _('Orders')


class Stream(TimeBasedModel):
    name = CharField(verbose_name=_('Name'), max_length=255)
    discount = PositiveIntegerField(verbose_name=_('Discount'), default=0, null=True, blank=True)
    visit_count = PositiveIntegerField(verbose_name=_('Amount of visits'), default=0)
    product = ForeignKey('apps.Product', CASCADE, verbose_name=_('Product'))
    owner = ForeignKey('apps.User', CASCADE, verbose_name=_('Owner'))

    class Meta:
        ordering = '-id',

    def __str__(self):
        return self.name

    @cached_property
    def changed_price(self):
        return self.product.price - self.discount

apps/views/product_views.py
from django.contrib import messages
from django.db.models import Sum, Q, F
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, FormView

from apps.forms import OrderModelForm
from apps.models import Category, Product, Stream, User, Order


class AllProductListView(ListView):
    queryset = Product.objects.select_related('category').order_by('-created_at')
    template_name = 'apps/index.html'
    context_object_name = 'products'
    paginate_by = 80

    def get_queryset(self):
        qs = super().get_queryset()
        search = self.request.GET.get('search')
        if search:
            qs = qs.filter(Q(name__icontains=search) | Q(description__icontains=search))
        return qs

    def get_context_data(self, *, object_list=None, **kwargs):
        ctx = super().get_context_data(object_list=object_list, **kwargs)
        ctx['categories'] = Category.objects.all()
        # Stream.objects.filter(owner=self.request.user, stream__orders__status=Order.Status.DELIVERING).annotate(
        #     price_=F('orders__product__product_fee') - F('discount')
        # ).aggregate(all_amount=Sum('price_'))

        ctx['coins'] = (User.objects.filter(id=self.request.user.pk).annotate(
            price_=F('stream__orders__product__product_fee') - F('stream__discount')).aggregate(
            all_amount=Sum('price_', filter=Q(stream__orders__status=Order.Status.DELIVERING))))
        return ctx


class ProductListView(ListView):
    queryset = Product.objects.all().order_by('-created_at')
    template_name = 'apps/product/product_list.html'
    context_object_name = 'products'
    paginate_by = 80

    def get_queryset(self):
        qs = super().get_queryset()
        category = self.request.GET.get('cat')
        search = self.request.GET.get('search')
        if category:
            return qs.filter(category__slug=category)
        if search:
            qs = qs.filter(Q(name__icontains=search) | Q(description__icontains=search))
        return qs

    def get_context_data(self, *, object_list=None, **kwargs):
        ctx = super().get_context_data(object_list=object_list, **kwargs)
        ctx['categories'] = Category.objects.all()
        return ctx


class ProductStreamDetail(DetailView, FormView):
    queryset = Product.objects.all()
    template_name = 'apps/product/product_detail.html'
    form_class = OrderModelForm
    success_url = reverse_lazy('order-detail')
    context_object_name = 'product'

    def get_object(self, queryset=None):
        self._stream_discount = 0
        pk = self.kwargs.get(self.pk_url_kwarg)
        if pk is not None:
            stream = get_object_or_404(Stream, pk=pk)
            stream.visit_count += 1
            self._stream_discount = -stream.discount
            stream.save()
            return stream.product
        return super().get_object(queryset)

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['discount'] = self._stream_discount
        ctx['stream_id'] = self.kwargs.get(self.pk_url_kwarg, '')
        ctx['range_1_to_9'] = range(1, 10)
        return ctx

    def form_valid(self, form):
        order = form.save()
        return redirect('order-detail', pk=order.id)

    def form_invalid(self, form):
        message = "Noto'g'ri telefon nomer !"
        messages.add_message(self.request, messages.WARNING, message)
        product_slug = form.cleaned_data.get('product').slug
        return redirect('product-detail', slug=product_slug)


class ProductSearchListView(ListView):
    queryset = Product.objects.all()
    template_name = 'apps/product/search_results.html'
    context_object_name = 'products'
    paginate_by = 3

    def get_queryset(self):
        qs = super().get_queryset()
        search = self.request.GET.get('search')
        if search:
            return qs.filter(name__icontains=search)
        return qs


class ProductStatisticListView(DetailView):
    queryset = Product.objects.all()
    template_name = 'apps/product/product_statistic.html'
    context_object_name = 'product'

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        session_product = Stream.objects.filter(product_id=self.kwargs.get('pk'), owner=self.request.user)
        ctx['my_stream_count'] = session_product.count()
        return ctx

templates/apps/product/product_detail.html
{% extends 'apps/base.html' %}
{% load humanize %}

{% block title %}
    | Mahsulot haqida |
{% endblock %}

{% block main_content %}
    <div class="card mb-3 mt-2">
        <div class="card-body">
            <!-- Product Form -->
            <div class="col-lg-8 swiper-container">
                <form action="{% url 'product-detail' product.slug %}" method="post">
                    {% csrf_token %}
                    <div class="mb-2">
                        <label class="form-label" for="formGroupNameInput">Ism:</label>
                        <input class="form-control" name="full_name" placeholder="Ismingizni kiriting:"
                               id="formGroupNameInput" required type="text">
                        <input class="form-control" name="product" type="hidden" value="{{ product.pk }}">
                        {% if user.is_authenticated %}
                            <input class="form-control" name="owner" type="hidden" value="{{ user.pk }}">
                            <input class="form-control" name="stream" type="hidden" value="{{ stream_id }}">
                        {% endif %}
                    </div>
                    <div class="mb-4">
                        <label class="form-label" for="phone-mask">Telefon nomer:</label>
                        {% if messages %}
                            {% for message in messages %}
                                <div class="alert alert-danger">{{ message }}</div>
                            {% endfor %}
                        {% endif %}
                        <input class="form-control" id="phone-mask" required
                               placeholder="Telefon raqamingizni kiriting:" name="phone" type="text">
                    </div>
                    <div class="mb-2">
                        <label class="form-label" for="formGroupAddressInput">Manzil:</label>
                        <input class="form-control" name="manzil" placeholder="Manzilni kiriting:"
                               id="formGroupAddressInput" required type="text">
                    </div>

                    <!-- Quantity with + and - buttons -->
                    <div class="mb-2">
                        <label class="form-label" for="formGroupQuantitySelect">Soni:</label>
                        <div class="input-group">
                            <button type="button" class="btn btn-outline-secondary" id="decrement">-</button>
                            <input type="number" class="form-control" name="quantity" id="quantity" value="1" min="1" max="9" required>
                            <button type="button" class="btn btn-outline-secondary" id="increment">+</button>
                        </div>
                    </div>

                    <div class="d-grid gap-2 col-6 mx-auto" style="margin-top: 20px;">
                        <button class="btn btn-primary" type="submit">Buyurtma berish</button>
                    </div>
                </form>
            </div>
            <br>
            <!-- Swiper Slider for Product Images -->
            <div class="row">
                <div class="col-lg-12">
                    <div class="swiper mySwiper">
                        <div class="swiper-wrapper">
                            <!-- Main Product Image -->
                            <div class="swiper-slide">
                                <img src="{{ product.photo.url }}" alt="{{ product.name }}"
                                     class="img-fluid image-uniform">
                            </div>
                            <!-- Additional Description Images -->
                            {% for image in product.description_images.all %}
                                <div class="swiper-slide">
                                    <img src="{{ image.image.url }}" alt="Description Image"
                                         class="img-fluid image-uniform">
                                </div>
                            {% endfor %}
                        </div>
                        <!-- Swiper Pagination -->
                        <div class="swiper-pagination"></div>
                    </div>
                </div>
            </div>
            <br>
            <div class="col-lg-8">
                <h5>{{ product.name }}</h5>
                <p>{{ product.description|safe }}</p>
                <h4 class="d-flex align-items-center">
                    <span class="text-warning me-2">
                        {{ product.price|add:discount|intcomma }} so'm
                    </span>
                </h4>
            </div>
        </div>
    </div>

    <!-- Include jQuery for Phone Mask -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.inputmask/5.0.7/jquery.inputmask.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.css"/>

    <script>
        $(document).ready(function () {
            $('#phone-mask').inputmask({
                "mask": "+998(99) 999-99-99"
            });
        });

        // Initialize Swiper with Auto-Slide
        const swiper = new Swiper('.mySwiper', {
            loop: true,  // Enable looping
            pagination: {
                el: '.swiper-pagination',
                clickable: true,
            },
            autoplay: {
                delay: 2000, // Auto-slide every 2 seconds
                disableOnInteraction: false, // Keep auto-sliding even if interacted
            },
        });

        // Quantity buttons
        $('#increment').click(function() {
            var quantity = $('#quantity').val();
            if (quantity < 9) {
                $('#quantity').val(parseInt(quantity) + 1);
            }
        });

        $('#decrement').click(function() {
            var quantity = $('#quantity').val();
            if (quantity > 1) {
                $('#quantity').val(parseInt(quantity) - 1);
            }
        });
    </script>

    <!-- Custom CSS -->
    <style>
        /* Make the description images fully responsive */
        .image-uniform {
            width: 100%; /* Ensures the image takes up the full width of its container */
            height: auto; /* Maintains aspect ratio */
            object-fit: contain; /* Ensures the image fits within its container without cropping */
            border-radius: 10px; /* Optional: adds rounded corners */
        }

        /* Adjust image display for smaller screens */
        @media (max-width: 768px) {
            .image-uniform {
                width: 100%; /* Ensures image takes up full width on small screens */
                height: 80%; /* Ensures aspect ratio is maintained on smaller screens */
            }
        }

        /* Custom styling for quantity input */
        .input-group {
            display: flex;
            align-items: center;
            width: 150px; /* Makes the width responsive */
            justify-content: center;
        }
        .input-group .form-control {
            width: 60px; /* Adjust width of the quantity input */
            text-align: center;
        }
        .input-group .btn {
            width: 40px;
            height: 40px;
            display: flex;
            align-items: center;
            justify-content: center;
        }
    </style>

{% endblock %}

templates/apps/product/product_statistic.html
{% extends 'apps/base.html' %}

{% block title %}
    | Mahsulot statistikasi |
{% endblock %}

{% block main_content %}
    <div class="card mb-3">
        <div class="card-body">

            <div class="container border-bottom-4">
                <div class="content_name_block">
                    <a href="{% url 'admin_page' %}" class="content_name_block_back">
                        <svg class="svg-inline--fa fa-arrow-right fa-w-14" aria-hidden="true" focusable="false"
                             data-prefix="fa" data-icon="arrow-right" role="img" xmlns="http://www.w3.org/2000/svg"
                             viewBox="0 0 448 512" data-fa-i2svg="">
                            <path fill="currentColor"
                                  d="M190.5 66.9l22.2-22.2c9.4-9.4 24.6-9.4 33.9 0L441 239c9.4 9.4 9.4 24.6 0 33.9L246.6 467.3c-9.4 9.4-24.6 9.4-33.9 0l-22.2-22.2c-9.5-9.5-9.3-25 .4-34.3L311.4 296H24c-13.3 0-24-10.7-24-24v-32c0-13.3 10.7-24 24-24h287.4L190.9 101.2c-9.8-9.3-10-24.8-.4-34.3z"></path>
                        </svg>
                        <!-- <span class="fa fa-arrow-right" aria-hidden="true"></span> Font Awesome fontawesome.com -->
                    </a>
                    <div class="content_name_block_text">
                        <h1>{{ product.name }} mahsuloti statistikasi</h1>
                    </div>
                </div>
            </div>
            <div class="container">

                <div class="content_favorite">
                    <div class="row">
                        <table class="table">
                            <thead>
                            <tr>
                                <th scope="col">Ma'lumot</th>
                                <th scope="col">Umumiy</th>
                                <th scope="col">Sizda</th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <td>Oqimlar</td>
                                <td>{{ product.stream_set.count }}</td>
                                <td>{{ my_stream_count }}</td>
                            </tr>
{#                            <tr>#}
{#                                <td>Admin bonusi</td>#}
{#                                <td>40000</td>#}
{#                                <td>40000</td>#}
{#                            </tr>#}
                            <tr>
                                <td>Mahsulot narxi</td>
                                <td>{{ product.price }}</td>
                                <td>{{ product.new_price }}</td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}